---
bindaddr: "localhost:5568"
name: "mqtt2sacn"
identifier: "mqtt2sacn"
mqtt:
  broker: ""
  port: 1883
  username: ""
  password: ""
  homeassistant: true
  homeass_prefix: "homeassistant/"
universe: 1
priority: 50
fixtures:
  - name: "Test wall orange"
    type: "dimmer"
    address: 19
    min_value: 10
  - name: "Test wall white"
    type: "dimmer"
    address: 21
    min_value: 10
